/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { VeriVoteMain } from "./VeriVoteMain";
export type { VoterRegistry } from "./VoterRegistry";
export * as factories from "./factories";
export { VeriVoteMain__factory } from "./factories/VeriVoteMain__factory";
export { VoterRegistry__factory } from "./factories/VoterRegistry__factory";
