/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace VeriVoteMain {
  export type CandidateStruct = {
    id: BigNumberish;
    name: string;
    description: string;
    imageHash: string;
    voteCount: BigNumberish;
  };

  export type CandidateStructOutput = [
    id: bigint,
    name: string,
    description: string,
    imageHash: string,
    voteCount: bigint
  ] & {
    id: bigint;
    name: string;
    description: string;
    imageHash: string;
    voteCount: bigint;
  };

  export type ElectionStruct = {
    id: BigNumberish;
    title: string;
    description: string;
    status: BigNumberish;
    createdBy: AddressLike;
    createdAt: BigNumberish;
    startDate: BigNumberish;
    endDate: BigNumberish;
    totalVoters: BigNumberish;
    totalVotes: BigNumberish;
    candidateCount: BigNumberish;
  };

  export type ElectionStructOutput = [
    id: bigint,
    title: string,
    description: string,
    status: bigint,
    createdBy: string,
    createdAt: bigint,
    startDate: bigint,
    endDate: bigint,
    totalVoters: bigint,
    totalVotes: bigint,
    candidateCount: bigint
  ] & {
    id: bigint;
    title: string;
    description: string;
    status: bigint;
    createdBy: string;
    createdAt: bigint;
    startDate: bigint;
    endDate: bigint;
    totalVoters: bigint;
    totalVotes: bigint;
    candidateCount: bigint;
  };
}

export interface VeriVoteMainInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addCandidate"
      | "addCandidatesBatch"
      | "candidates"
      | "castVote"
      | "castVoteByAdmin"
      | "createElection"
      | "electionCount"
      | "electionVotes"
      | "elections"
      | "endElection"
      | "getAllCandidates"
      | "getCandidate"
      | "getElection"
      | "getElectionCount"
      | "getElectionResults"
      | "getElectionVoteCount"
      | "getParticipationRate"
      | "getVoteVerification"
      | "hasVoted"
      | "hasVoterVoted"
      | "isElectionActive"
      | "owner"
      | "startElection"
      | "voteRecords"
      | "voterRegistry"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CandidateAdded"
      | "ElectionCreated"
      | "ElectionEnded"
      | "ElectionStarted"
      | "ElectionStatusChanged"
      | "VoteCast"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addCandidate",
    values: [BigNumberish, string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "addCandidatesBatch",
    values: [BigNumberish, string[], string[], string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "candidates",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "castVote",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "castVoteByAdmin",
    values: [BigNumberish, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createElection",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "electionCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "electionVotes",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "elections",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "endElection",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllCandidates",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCandidate",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getElection",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getElectionCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getElectionResults",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getElectionVoteCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getParticipationRate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getVoteVerification",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasVoted",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasVoterVoted",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isElectionActive",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "startElection",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "voteRecords",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "voterRegistry",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "addCandidate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addCandidatesBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "candidates", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "castVote", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "castVoteByAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createElection",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "electionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "electionVotes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "elections", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "endElection",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllCandidates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCandidate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getElection",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getElectionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getElectionResults",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getElectionVoteCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getParticipationRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVoteVerification",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasVoted", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hasVoterVoted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isElectionActive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "startElection",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "voteRecords",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "voterRegistry",
    data: BytesLike
  ): Result;
}

export namespace CandidateAddedEvent {
  export type InputTuple = [
    electionId: BigNumberish,
    candidateId: BigNumberish,
    name: string
  ];
  export type OutputTuple = [
    electionId: bigint,
    candidateId: bigint,
    name: string
  ];
  export interface OutputObject {
    electionId: bigint;
    candidateId: bigint;
    name: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ElectionCreatedEvent {
  export type InputTuple = [
    electionId: BigNumberish,
    title: string,
    createdBy: AddressLike
  ];
  export type OutputTuple = [
    electionId: bigint,
    title: string,
    createdBy: string
  ];
  export interface OutputObject {
    electionId: bigint;
    title: string;
    createdBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ElectionEndedEvent {
  export type InputTuple = [electionId: BigNumberish, totalVotes: BigNumberish];
  export type OutputTuple = [electionId: bigint, totalVotes: bigint];
  export interface OutputObject {
    electionId: bigint;
    totalVotes: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ElectionStartedEvent {
  export type InputTuple = [
    electionId: BigNumberish,
    startDate: BigNumberish,
    endDate: BigNumberish
  ];
  export type OutputTuple = [
    electionId: bigint,
    startDate: bigint,
    endDate: bigint
  ];
  export interface OutputObject {
    electionId: bigint;
    startDate: bigint;
    endDate: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ElectionStatusChangedEvent {
  export type InputTuple = [
    electionId: BigNumberish,
    oldStatus: BigNumberish,
    newStatus: BigNumberish
  ];
  export type OutputTuple = [
    electionId: bigint,
    oldStatus: bigint,
    newStatus: bigint
  ];
  export interface OutputObject {
    electionId: bigint;
    oldStatus: bigint;
    newStatus: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoteCastEvent {
  export type InputTuple = [
    electionId: BigNumberish,
    voter: AddressLike,
    voteHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    electionId: bigint,
    voter: string,
    voteHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    electionId: bigint;
    voter: string;
    voteHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface VeriVoteMain extends BaseContract {
  connect(runner?: ContractRunner | null): VeriVoteMain;
  waitForDeployment(): Promise<this>;

  interface: VeriVoteMainInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addCandidate: TypedContractMethod<
    [
      _electionId: BigNumberish,
      _name: string,
      _description: string,
      _imageHash: string
    ],
    [bigint],
    "nonpayable"
  >;

  addCandidatesBatch: TypedContractMethod<
    [
      _electionId: BigNumberish,
      _names: string[],
      _descriptions: string[],
      _imageHashes: string[]
    ],
    [void],
    "nonpayable"
  >;

  candidates: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [bigint, string, string, string, bigint] & {
        id: bigint;
        name: string;
        description: string;
        imageHash: string;
        voteCount: bigint;
      }
    ],
    "view"
  >;

  castVote: TypedContractMethod<
    [_electionId: BigNumberish, _candidateId: BigNumberish],
    [void],
    "nonpayable"
  >;

  castVoteByAdmin: TypedContractMethod<
    [
      _electionId: BigNumberish,
      _candidateId: BigNumberish,
      _voter: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  createElection: TypedContractMethod<
    [_title: string, _description: string, _totalVoters: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  electionCount: TypedContractMethod<[], [bigint], "view">;

  electionVotes: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [string, bigint, bigint, string] & {
        voter: string;
        candidateId: bigint;
        timestamp: bigint;
        voteHash: string;
      }
    ],
    "view"
  >;

  elections: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        id: bigint;
        title: string;
        description: string;
        status: bigint;
        createdBy: string;
        createdAt: bigint;
        startDate: bigint;
        endDate: bigint;
        totalVoters: bigint;
        totalVotes: bigint;
        candidateCount: bigint;
      }
    ],
    "view"
  >;

  endElection: TypedContractMethod<
    [_electionId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getAllCandidates: TypedContractMethod<
    [_electionId: BigNumberish],
    [VeriVoteMain.CandidateStructOutput[]],
    "view"
  >;

  getCandidate: TypedContractMethod<
    [_electionId: BigNumberish, _candidateId: BigNumberish],
    [VeriVoteMain.CandidateStructOutput],
    "view"
  >;

  getElection: TypedContractMethod<
    [_electionId: BigNumberish],
    [VeriVoteMain.ElectionStructOutput],
    "view"
  >;

  getElectionCount: TypedContractMethod<[], [bigint], "view">;

  getElectionResults: TypedContractMethod<
    [_electionId: BigNumberish],
    [VeriVoteMain.CandidateStructOutput[]],
    "view"
  >;

  getElectionVoteCount: TypedContractMethod<
    [_electionId: BigNumberish],
    [bigint],
    "view"
  >;

  getParticipationRate: TypedContractMethod<
    [_electionId: BigNumberish],
    [bigint],
    "view"
  >;

  getVoteVerification: TypedContractMethod<
    [_electionId: BigNumberish, _voter: AddressLike],
    [string],
    "view"
  >;

  hasVoted: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  hasVoterVoted: TypedContractMethod<
    [_electionId: BigNumberish, _voter: AddressLike],
    [boolean],
    "view"
  >;

  isElectionActive: TypedContractMethod<
    [_electionId: BigNumberish],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  startElection: TypedContractMethod<
    [_electionId: BigNumberish, _durationInSeconds: BigNumberish],
    [void],
    "nonpayable"
  >;

  voteRecords: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [
      [string, bigint, bigint, string] & {
        voter: string;
        candidateId: bigint;
        timestamp: bigint;
        voteHash: string;
      }
    ],
    "view"
  >;

  voterRegistry: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addCandidate"
  ): TypedContractMethod<
    [
      _electionId: BigNumberish,
      _name: string,
      _description: string,
      _imageHash: string
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addCandidatesBatch"
  ): TypedContractMethod<
    [
      _electionId: BigNumberish,
      _names: string[],
      _descriptions: string[],
      _imageHashes: string[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "candidates"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [bigint, string, string, string, bigint] & {
        id: bigint;
        name: string;
        description: string;
        imageHash: string;
        voteCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "castVote"
  ): TypedContractMethod<
    [_electionId: BigNumberish, _candidateId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "castVoteByAdmin"
  ): TypedContractMethod<
    [
      _electionId: BigNumberish,
      _candidateId: BigNumberish,
      _voter: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createElection"
  ): TypedContractMethod<
    [_title: string, _description: string, _totalVoters: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "electionCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "electionVotes"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [string, bigint, bigint, string] & {
        voter: string;
        candidateId: bigint;
        timestamp: bigint;
        voteHash: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "elections"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        id: bigint;
        title: string;
        description: string;
        status: bigint;
        createdBy: string;
        createdAt: bigint;
        startDate: bigint;
        endDate: bigint;
        totalVoters: bigint;
        totalVotes: bigint;
        candidateCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "endElection"
  ): TypedContractMethod<[_electionId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAllCandidates"
  ): TypedContractMethod<
    [_electionId: BigNumberish],
    [VeriVoteMain.CandidateStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCandidate"
  ): TypedContractMethod<
    [_electionId: BigNumberish, _candidateId: BigNumberish],
    [VeriVoteMain.CandidateStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getElection"
  ): TypedContractMethod<
    [_electionId: BigNumberish],
    [VeriVoteMain.ElectionStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getElectionCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getElectionResults"
  ): TypedContractMethod<
    [_electionId: BigNumberish],
    [VeriVoteMain.CandidateStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getElectionVoteCount"
  ): TypedContractMethod<[_electionId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getParticipationRate"
  ): TypedContractMethod<[_electionId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getVoteVerification"
  ): TypedContractMethod<
    [_electionId: BigNumberish, _voter: AddressLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasVoted"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasVoterVoted"
  ): TypedContractMethod<
    [_electionId: BigNumberish, _voter: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isElectionActive"
  ): TypedContractMethod<[_electionId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "startElection"
  ): TypedContractMethod<
    [_electionId: BigNumberish, _durationInSeconds: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "voteRecords"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [
      [string, bigint, bigint, string] & {
        voter: string;
        candidateId: bigint;
        timestamp: bigint;
        voteHash: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "voterRegistry"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "CandidateAdded"
  ): TypedContractEvent<
    CandidateAddedEvent.InputTuple,
    CandidateAddedEvent.OutputTuple,
    CandidateAddedEvent.OutputObject
  >;
  getEvent(
    key: "ElectionCreated"
  ): TypedContractEvent<
    ElectionCreatedEvent.InputTuple,
    ElectionCreatedEvent.OutputTuple,
    ElectionCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ElectionEnded"
  ): TypedContractEvent<
    ElectionEndedEvent.InputTuple,
    ElectionEndedEvent.OutputTuple,
    ElectionEndedEvent.OutputObject
  >;
  getEvent(
    key: "ElectionStarted"
  ): TypedContractEvent<
    ElectionStartedEvent.InputTuple,
    ElectionStartedEvent.OutputTuple,
    ElectionStartedEvent.OutputObject
  >;
  getEvent(
    key: "ElectionStatusChanged"
  ): TypedContractEvent<
    ElectionStatusChangedEvent.InputTuple,
    ElectionStatusChangedEvent.OutputTuple,
    ElectionStatusChangedEvent.OutputObject
  >;
  getEvent(
    key: "VoteCast"
  ): TypedContractEvent<
    VoteCastEvent.InputTuple,
    VoteCastEvent.OutputTuple,
    VoteCastEvent.OutputObject
  >;

  filters: {
    "CandidateAdded(uint256,uint256,string)": TypedContractEvent<
      CandidateAddedEvent.InputTuple,
      CandidateAddedEvent.OutputTuple,
      CandidateAddedEvent.OutputObject
    >;
    CandidateAdded: TypedContractEvent<
      CandidateAddedEvent.InputTuple,
      CandidateAddedEvent.OutputTuple,
      CandidateAddedEvent.OutputObject
    >;

    "ElectionCreated(uint256,string,address)": TypedContractEvent<
      ElectionCreatedEvent.InputTuple,
      ElectionCreatedEvent.OutputTuple,
      ElectionCreatedEvent.OutputObject
    >;
    ElectionCreated: TypedContractEvent<
      ElectionCreatedEvent.InputTuple,
      ElectionCreatedEvent.OutputTuple,
      ElectionCreatedEvent.OutputObject
    >;

    "ElectionEnded(uint256,uint256)": TypedContractEvent<
      ElectionEndedEvent.InputTuple,
      ElectionEndedEvent.OutputTuple,
      ElectionEndedEvent.OutputObject
    >;
    ElectionEnded: TypedContractEvent<
      ElectionEndedEvent.InputTuple,
      ElectionEndedEvent.OutputTuple,
      ElectionEndedEvent.OutputObject
    >;

    "ElectionStarted(uint256,uint256,uint256)": TypedContractEvent<
      ElectionStartedEvent.InputTuple,
      ElectionStartedEvent.OutputTuple,
      ElectionStartedEvent.OutputObject
    >;
    ElectionStarted: TypedContractEvent<
      ElectionStartedEvent.InputTuple,
      ElectionStartedEvent.OutputTuple,
      ElectionStartedEvent.OutputObject
    >;

    "ElectionStatusChanged(uint256,uint8,uint8)": TypedContractEvent<
      ElectionStatusChangedEvent.InputTuple,
      ElectionStatusChangedEvent.OutputTuple,
      ElectionStatusChangedEvent.OutputObject
    >;
    ElectionStatusChanged: TypedContractEvent<
      ElectionStatusChangedEvent.InputTuple,
      ElectionStatusChangedEvent.OutputTuple,
      ElectionStatusChangedEvent.OutputObject
    >;

    "VoteCast(uint256,address,bytes32,uint256)": TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;
    VoteCast: TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;
  };
}
