/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace VoterRegistry {
  export type VoterStruct = {
    nim: string;
    name: string;
    role: BigNumberish;
    isRegistered: boolean;
    registeredAt: BigNumberish;
  };

  export type VoterStructOutput = [
    nim: string,
    name: string,
    role: bigint,
    isRegistered: boolean,
    registeredAt: bigint
  ] & {
    nim: string;
    name: string;
    role: bigint;
    isRegistered: boolean;
    registeredAt: bigint;
  };
}

export interface VoterRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "batchRegisterVoters"
      | "getAddressByNim"
      | "getAllVoterAddresses"
      | "getVoterByAddress"
      | "getVoterByNim"
      | "getVoterCount"
      | "getVoterRole"
      | "isRegistered"
      | "nimToAddress"
      | "owner"
      | "registerVoter"
      | "removeVoter"
      | "totalVoters"
      | "updateVoterRole"
      | "voterAddresses"
      | "voters"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "VoterRegistered"
      | "VoterRemoved"
      | "VoterRoleUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "batchRegisterVoters",
    values: [AddressLike[], string[], string[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getAddressByNim",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllVoterAddresses",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getVoterByAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVoterByNim",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getVoterCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getVoterRole",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isRegistered",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "nimToAddress",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerVoter",
    values: [AddressLike, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "removeVoter",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalVoters",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateVoterRole",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "voterAddresses",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "voters", values: [AddressLike]): string;

  decodeFunctionResult(
    functionFragment: "batchRegisterVoters",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAddressByNim",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllVoterAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVoterByAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVoterByNim",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVoterCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVoterRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nimToAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerVoter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeVoter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalVoters",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateVoterRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "voterAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "voters", data: BytesLike): Result;
}

export namespace VoterRegisteredEvent {
  export type InputTuple = [
    voterAddress: AddressLike,
    nim: string,
    name: string,
    role: BigNumberish
  ];
  export type OutputTuple = [
    voterAddress: string,
    nim: string,
    name: string,
    role: bigint
  ];
  export interface OutputObject {
    voterAddress: string;
    nim: string;
    name: string;
    role: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoterRemovedEvent {
  export type InputTuple = [voterAddress: AddressLike, nim: string];
  export type OutputTuple = [voterAddress: string, nim: string];
  export interface OutputObject {
    voterAddress: string;
    nim: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoterRoleUpdatedEvent {
  export type InputTuple = [
    voterAddress: AddressLike,
    oldRole: BigNumberish,
    newRole: BigNumberish
  ];
  export type OutputTuple = [
    voterAddress: string,
    oldRole: bigint,
    newRole: bigint
  ];
  export interface OutputObject {
    voterAddress: string;
    oldRole: bigint;
    newRole: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface VoterRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): VoterRegistry;
  waitForDeployment(): Promise<this>;

  interface: VoterRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  batchRegisterVoters: TypedContractMethod<
    [
      _addresses: AddressLike[],
      _nims: string[],
      _names: string[],
      _roles: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;

  getAddressByNim: TypedContractMethod<[_nim: string], [string], "view">;

  getAllVoterAddresses: TypedContractMethod<[], [string[]], "view">;

  getVoterByAddress: TypedContractMethod<
    [_address: AddressLike],
    [VoterRegistry.VoterStructOutput],
    "view"
  >;

  getVoterByNim: TypedContractMethod<
    [_nim: string],
    [VoterRegistry.VoterStructOutput],
    "view"
  >;

  getVoterCount: TypedContractMethod<[], [bigint], "view">;

  getVoterRole: TypedContractMethod<[_address: AddressLike], [bigint], "view">;

  isRegistered: TypedContractMethod<[_address: AddressLike], [boolean], "view">;

  nimToAddress: TypedContractMethod<[arg0: string], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  registerVoter: TypedContractMethod<
    [
      _voterAddress: AddressLike,
      _nim: string,
      _name: string,
      _role: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  removeVoter: TypedContractMethod<
    [_voterAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  totalVoters: TypedContractMethod<[], [bigint], "view">;

  updateVoterRole: TypedContractMethod<
    [_voterAddress: AddressLike, _newRole: BigNumberish],
    [void],
    "nonpayable"
  >;

  voterAddresses: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  voters: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, bigint, boolean, bigint] & {
        nim: string;
        name: string;
        role: bigint;
        isRegistered: boolean;
        registeredAt: bigint;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "batchRegisterVoters"
  ): TypedContractMethod<
    [
      _addresses: AddressLike[],
      _nims: string[],
      _names: string[],
      _roles: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAddressByNim"
  ): TypedContractMethod<[_nim: string], [string], "view">;
  getFunction(
    nameOrSignature: "getAllVoterAddresses"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getVoterByAddress"
  ): TypedContractMethod<
    [_address: AddressLike],
    [VoterRegistry.VoterStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVoterByNim"
  ): TypedContractMethod<
    [_nim: string],
    [VoterRegistry.VoterStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVoterCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getVoterRole"
  ): TypedContractMethod<[_address: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "isRegistered"
  ): TypedContractMethod<[_address: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "nimToAddress"
  ): TypedContractMethod<[arg0: string], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerVoter"
  ): TypedContractMethod<
    [
      _voterAddress: AddressLike,
      _nim: string,
      _name: string,
      _role: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removeVoter"
  ): TypedContractMethod<[_voterAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalVoters"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "updateVoterRole"
  ): TypedContractMethod<
    [_voterAddress: AddressLike, _newRole: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "voterAddresses"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "voters"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, bigint, boolean, bigint] & {
        nim: string;
        name: string;
        role: bigint;
        isRegistered: boolean;
        registeredAt: bigint;
      }
    ],
    "view"
  >;

  getEvent(
    key: "VoterRegistered"
  ): TypedContractEvent<
    VoterRegisteredEvent.InputTuple,
    VoterRegisteredEvent.OutputTuple,
    VoterRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "VoterRemoved"
  ): TypedContractEvent<
    VoterRemovedEvent.InputTuple,
    VoterRemovedEvent.OutputTuple,
    VoterRemovedEvent.OutputObject
  >;
  getEvent(
    key: "VoterRoleUpdated"
  ): TypedContractEvent<
    VoterRoleUpdatedEvent.InputTuple,
    VoterRoleUpdatedEvent.OutputTuple,
    VoterRoleUpdatedEvent.OutputObject
  >;

  filters: {
    "VoterRegistered(address,string,string,uint8)": TypedContractEvent<
      VoterRegisteredEvent.InputTuple,
      VoterRegisteredEvent.OutputTuple,
      VoterRegisteredEvent.OutputObject
    >;
    VoterRegistered: TypedContractEvent<
      VoterRegisteredEvent.InputTuple,
      VoterRegisteredEvent.OutputTuple,
      VoterRegisteredEvent.OutputObject
    >;

    "VoterRemoved(address,string)": TypedContractEvent<
      VoterRemovedEvent.InputTuple,
      VoterRemovedEvent.OutputTuple,
      VoterRemovedEvent.OutputObject
    >;
    VoterRemoved: TypedContractEvent<
      VoterRemovedEvent.InputTuple,
      VoterRemovedEvent.OutputTuple,
      VoterRemovedEvent.OutputObject
    >;

    "VoterRoleUpdated(address,uint8,uint8)": TypedContractEvent<
      VoterRoleUpdatedEvent.InputTuple,
      VoterRoleUpdatedEvent.OutputTuple,
      VoterRoleUpdatedEvent.OutputObject
    >;
    VoterRoleUpdated: TypedContractEvent<
      VoterRoleUpdatedEvent.InputTuple,
      VoterRoleUpdatedEvent.OutputTuple,
      VoterRoleUpdatedEvent.OutputObject
    >;
  };
}
