/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { VeriVoteMain__factory } from "./VeriVoteMain__factory";
export { VoterRegistry__factory } from "./VoterRegistry__factory";
